# Generated by Django 2.0.3 on 2018-12-23 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemGroup', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('extras', models.ManyToManyField(blank=True, related_name='topings', to='orders.Extras')),
                ('itemGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ItemGroup')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='itemGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ItemGroup'),
        ),
        migrations.AddField(
            model_name='extras',
            name='itemGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ItemGroup'),
        ),
    ]
