# Generated by Django 2.0.3 on 2019-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='customizable',
            field=models.BooleanField(default=False),
        ),
    ]
