# Generated by Django 2.0.3 on 2018-12-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181222_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='itemGroup',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('itemName', 'size', 'itemGroup')},
        ),
    ]
